#!/usr/bin/expect -f

spawn git push -u origin master
expect "Username for 'https://github.com':"
send -- "weeklyupdates\r"
expect "Password for 'https://weeklyupdates@github.com':"
interact ++ return
expect EOF
